-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. User Management & RBAC
create table if not exists public.staff_users (
    id uuid default uuid_generate_v4() primary key,
    user_id uuid references auth.users(id) on delete cascade not null,
    role text not null check (role in ('admin', 'doctor', 'staff')),
    name text,
    created_at timestamptz default now(),
    unique(user_id)
);

create table if not exists public.audit_logs (
    id uuid default uuid_generate_v4() primary key,
    user_id uuid references auth.users(id),
    action text not null,
    details jsonb,
    created_at timestamptz default now()
);

-- 2. Chat System (Persistence)
create table if not exists public.chat_sessions (
    id uuid default uuid_generate_v4() primary key,
    user_id uuid references auth.users(id) on delete set null,
    topic text not null, -- e.g., 'smile_test', 'breath_mbti'
    title text,
    created_at timestamptz default now(),
    updated_at timestamptz default now()
);

create table if not exists public.chat_messages (
    id uuid default uuid_generate_v4() primary key,
    session_id uuid references public.chat_sessions(id) on delete cascade not null,
    role text not null check (role in ('user', 'assistant', 'system')),
    content text not null,
    created_at timestamptz default now()
);

-- 3. Patient Care (EMR)
-- Note: 'patients' table might already exist from previous migration, using if not exists
create table if not exists public.patients (
    id bigint generated by default as identity primary key,
    created_at timestamptz default now(),
    name text not null,
    birth_date date,
    gender text,
    phone text,
    email text,
    address text,
    medical_history text,
    status text check (status in ('pending', 'active', 'archived')) default 'active'
);

create table if not exists public.visits (
    id uuid default uuid_generate_v4() primary key,
    patient_id bigint references public.patients(id) on delete cascade not null,
    visit_date timestamptz default now(),
    visit_type text not null, -- e.g., 'consultation', 'treatment', 'checkup'
    status text check (status in ('scheduled', 'in_progress', 'completed', 'cancelled')) default 'scheduled',
    chief_complaint text,
    created_at timestamptz default now()
);

create table if not exists public.clinical_notes (
    id uuid default uuid_generate_v4() primary key,
    visit_id uuid references public.visits(id) on delete cascade not null,
    author_id uuid references auth.users(id),
    content text not null,
    note_type text default 'general', -- 'soap', 'procedure', etc.
    created_at timestamptz default now(),
    updated_at timestamptz default now()
);

create table if not exists public.clinical_images (
    id uuid default uuid_generate_v4() primary key,
    visit_id uuid references public.visits(id) on delete cascade,
    patient_id bigint references public.patients(id) on delete cascade,
    image_url text not null,
    analysis_result jsonb,
    created_at timestamptz default now()
);

create table if not exists public.treatment_plans (
    id uuid default uuid_generate_v4() primary key,
    patient_id bigint references public.patients(id) on delete cascade not null,
    title text not null,
    description text,
    estimated_cost numeric,
    status text check (status in ('proposed', 'accepted', 'completed', 'declined')) default 'proposed',
    created_at timestamptz default now(),
    updated_at timestamptz default now()
);

-- 4. Analysis & Intake
create table if not exists public.intake_summaries (
    id uuid default uuid_generate_v4() primary key,
    user_id uuid references auth.users(id) on delete set null,
    flow_type text not null,
    summary text not null,
    raw_data jsonb,
    created_at timestamptz default now()
);

-- 5. RLS Policies
alter table public.staff_users enable row level security;
alter table public.audit_logs enable row level security;
alter table public.chat_sessions enable row level security;
alter table public.chat_messages enable row level security;
alter table public.patients enable row level security;
alter table public.visits enable row level security;
alter table public.clinical_notes enable row level security;
alter table public.clinical_images enable row level security;
alter table public.treatment_plans enable row level security;
alter table public.intake_summaries enable row level security;

-- Simple policies for demo (Open read/write for authenticated users or public as needed)
-- In production, these should be stricter.

-- Staff Users: Read-only for everyone (to check roles), Write for admins only
create policy "Allow read access for all users" on public.staff_users for select using (true);
create policy "Allow write access for admins" on public.staff_users for insert with check (
    exists (select 1 from public.staff_users where user_id = auth.uid() and role = 'admin')
);

-- Chat: Users can see their own chats
create policy "Users can view own sessions" on public.chat_sessions for select using (auth.uid() = user_id);
create policy "Users can insert own sessions" on public.chat_sessions for insert with check (auth.uid() = user_id);
create policy "Users can view own messages" on public.chat_messages for select using (
    exists (select 1 from public.chat_sessions where id = chat_messages.session_id and user_id = auth.uid())
);
create policy "Users can insert own messages" on public.chat_messages for insert with check (
    exists (select 1 from public.chat_sessions where id = chat_messages.session_id and user_id = auth.uid())
);

-- EMR Tables: Staff can view/edit all, Patients can view their own (if linked)
-- For this MVP, we'll allow authenticated users (staff) to access EMR data
create policy "Staff can view patients" on public.patients for select using (auth.role() = 'authenticated');
create policy "Staff can edit patients" on public.patients for all using (auth.role() = 'authenticated');

-- 6. Insert Admin User
-- UID: 0e63bd13-ca1d-4f87-a8da-85fd408e3ede
-- Email: admin@admin.com
do $$
begin
    if not exists (select 1 from public.staff_users where user_id = '0e63bd13-ca1d-4f87-a8da-85fd408e3ede') then
        insert into public.staff_users (user_id, role, name)
        values ('0e63bd13-ca1d-4f87-a8da-85fd408e3ede', 'admin', 'System Admin');
    end if;
end $$;
